# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/CortexA9_AXI_GPIO/CortexA9_AXI_GPIO.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CortexA9_AXI_GPIO || ORIG_REF_NAME==CortexA9_AXI_GPIO} -quiet] -quiet

# IP: bd/CortexA9_AXI_GPIO/ip/CortexA9_AXI_GPIO_processing_system7_0_0/CortexA9_AXI_GPIO_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CortexA9_AXI_GPIO_processing_system7_0_0 || ORIG_REF_NAME==CortexA9_AXI_GPIO_processing_system7_0_0} -quiet] -quiet

# IP: bd/CortexA9_AXI_GPIO/ip/CortexA9_AXI_GPIO_axi_gpio_0_0/CortexA9_AXI_GPIO_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CortexA9_AXI_GPIO_axi_gpio_0_0 || ORIG_REF_NAME==CortexA9_AXI_GPIO_axi_gpio_0_0} -quiet] -quiet

# IP: bd/CortexA9_AXI_GPIO/ip/CortexA9_AXI_GPIO_axi_gpio_0_1/CortexA9_AXI_GPIO_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CortexA9_AXI_GPIO_axi_gpio_0_1 || ORIG_REF_NAME==CortexA9_AXI_GPIO_axi_gpio_0_1} -quiet] -quiet

# IP: bd/CortexA9_AXI_GPIO/ip/CortexA9_AXI_GPIO_axi_gpio_0_2/CortexA9_AXI_GPIO_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CortexA9_AXI_GPIO_axi_gpio_0_2 || ORIG_REF_NAME==CortexA9_AXI_GPIO_axi_gpio_0_2} -quiet] -quiet

# IP: bd/CortexA9_AXI_GPIO/ip/CortexA9_AXI_GPIO_xbar_0/CortexA9_AXI_GPIO_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CortexA9_AXI_GPIO_xbar_0 || ORIG_REF_NAME==CortexA9_AXI_GPIO_xbar_0} -quiet] -quiet

# IP: bd/CortexA9_AXI_GPIO/ip/CortexA9_AXI_GPIO_auto_pc_0/CortexA9_AXI_GPIO_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CortexA9_AXI_GPIO_auto_pc_0 || ORIG_REF_NAME==CortexA9_AXI_GPIO_auto_pc_0} -quiet] -quiet

# IP: bd/CortexA9_AXI_GPIO/ip/CortexA9_AXI_GPIO_ps7_0_axi_periph_0/CortexA9_AXI_GPIO_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CortexA9_AXI_GPIO_ps7_0_axi_periph_0 || ORIG_REF_NAME==CortexA9_AXI_GPIO_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/CortexA9_AXI_GPIO/ip/CortexA9_AXI_GPIO_rst_ps7_0_50M_0/CortexA9_AXI_GPIO_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CortexA9_AXI_GPIO_rst_ps7_0_50M_0 || ORIG_REF_NAME==CortexA9_AXI_GPIO_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/Users/dcapr/vhdl-fpga-udemy/lesson_6/PS_CortexA9_AXI_GPIO/PS_CortexA9_AXI_GPIO.gen/sources_1/bd/CortexA9_AXI_GPIO/CortexA9_AXI_GPIO_ooc.xdc
