domain_path: C:\Users\dcapr\vhdl-fpga-udemy\lesson_5\CortexA9_Z7\export\CortexA9_Z7\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
