# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/CortexA9/CortexA9.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CortexA9 || ORIG_REF_NAME==CortexA9} -quiet] -quiet

# IP: bd/CortexA9/ip/CortexA9_processing_system7_0_0/CortexA9_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CortexA9_processing_system7_0_0 || ORIG_REF_NAME==CortexA9_processing_system7_0_0} -quiet] -quiet

# XDC: c:/Users/dcapr/vhdl-fpga-udemy/lesson_5/PS_CortexA9_Implementation/PS_CortexA9_Implementation.gen/sources_1/bd/CortexA9/CortexA9_ooc.xdc
