# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/dcapr/vhdl-fpga-udemy/lesson_6/PS_CortexA9_AXI_GPIO/PS_CortexA9_AXI_GPIO.srcs/sources_1/bd/CortexA9_AXI_GPIO/ip/CortexA9_AXI_GPIO_axi_gpio_0_1/CortexA9_AXI_GPIO_axi_gpio_0_1.xci
# IP: The module: 'CortexA9_AXI_GPIO_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dcapr/vhdl-fpga-udemy/lesson_6/PS_CortexA9_AXI_GPIO/PS_CortexA9_AXI_GPIO.gen/sources_1/bd/CortexA9_AXI_GPIO/ip/CortexA9_AXI_GPIO_axi_gpio_0_1/CortexA9_AXI_GPIO_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CortexA9_AXI_GPIO_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dcapr/vhdl-fpga-udemy/lesson_6/PS_CortexA9_AXI_GPIO/PS_CortexA9_AXI_GPIO.gen/sources_1/bd/CortexA9_AXI_GPIO/ip/CortexA9_AXI_GPIO_axi_gpio_0_1/CortexA9_AXI_GPIO_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CortexA9_AXI_GPIO_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dcapr/vhdl-fpga-udemy/lesson_6/PS_CortexA9_AXI_GPIO/PS_CortexA9_AXI_GPIO.gen/sources_1/bd/CortexA9_AXI_GPIO/ip/CortexA9_AXI_GPIO_axi_gpio_0_1/CortexA9_AXI_GPIO_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'CortexA9_AXI_GPIO_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/dcapr/vhdl-fpga-udemy/lesson_6/PS_CortexA9_AXI_GPIO/PS_CortexA9_AXI_GPIO.srcs/sources_1/bd/CortexA9_AXI_GPIO/ip/CortexA9_AXI_GPIO_axi_gpio_0_1/CortexA9_AXI_GPIO_axi_gpio_0_1.xci
# IP: The module: 'CortexA9_AXI_GPIO_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dcapr/vhdl-fpga-udemy/lesson_6/PS_CortexA9_AXI_GPIO/PS_CortexA9_AXI_GPIO.gen/sources_1/bd/CortexA9_AXI_GPIO/ip/CortexA9_AXI_GPIO_axi_gpio_0_1/CortexA9_AXI_GPIO_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CortexA9_AXI_GPIO_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dcapr/vhdl-fpga-udemy/lesson_6/PS_CortexA9_AXI_GPIO/PS_CortexA9_AXI_GPIO.gen/sources_1/bd/CortexA9_AXI_GPIO/ip/CortexA9_AXI_GPIO_axi_gpio_0_1/CortexA9_AXI_GPIO_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CortexA9_AXI_GPIO_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dcapr/vhdl-fpga-udemy/lesson_6/PS_CortexA9_AXI_GPIO/PS_CortexA9_AXI_GPIO.gen/sources_1/bd/CortexA9_AXI_GPIO/ip/CortexA9_AXI_GPIO_axi_gpio_0_1/CortexA9_AXI_GPIO_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'CortexA9_AXI_GPIO_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
